-- SCHEMA: agenda

-- DROP SCHEMA IF EXISTS agenda ;

CREATE SCHEMA IF NOT EXISTS agenda
    AUTHORIZATION postgres;-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS agenda.contacto
(
    id serial NOT NULL,
    nombre character varying(50) NOT NULL,
    numero_documento character varying(20) NOT NULL,
    direccion character varying(50) NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_modificacion timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS agenda.telefono
(
    id serial NOT NULL,
    contacto_id integer,
    telefono character varying(20) NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_modificacion timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS agenda.correo
(
    id serial NOT NULL,
    contacto_id integer,
    email character varying(30) NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_modificacion timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS agenda.telefono
    ADD CONSTRAINT pk_telefono_contacto FOREIGN KEY (contacto_id)
    REFERENCES agenda.contacto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS agenda.correo
    ADD CONSTRAINT pk_correo_contacto FOREIGN KEY (contacto_id)
    REFERENCES agenda.contacto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;

-- Insertar valores en la tabla 'contacto'
INSERT INTO agenda.contacto (nombre, numero_documento, direccion, fecha_creacion, fecha_modificacion)
VALUES
    ('Juan Pérez', '123456789', 'Calle 123, Ciudad', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('María López', '987654321', 'Avenida 456, Ciudad', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insertar valores en la tabla 'telefono'
INSERT INTO agenda.telefono (contacto_id, telefono, fecha_creacion, fecha_modificacion)
VALUES
    (1, '555-1234', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (1, '555-5678', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, '555-8765', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insertar valores en la tabla 'correo'
INSERT INTO agenda.correo (contacto_id, email, fecha_creacion, fecha_modificacion)
VALUES
    (1, 'juan@example.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (1, 'juan.perez@example.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 'maria@example.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
